name: flutter_sample
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  countup: ^0.1.4
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.9.0
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.6.1
  http: ^1.3.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.4
  yumemi_lints: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#add8e6"
  image: "assets/images/splash.png"
  color_dark: "#262626"
  image_dark: "assets/images/splash.png"
  fullscreen: true
