// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEMHXFVz9FaGJOzUcjRX3qmODSuw3b6VI',
    appId: '1:859187312433:web:a4cc1b10ad4909a5f96210',
    messagingSenderId: '859187312433',
    projectId: 'fluttersample-29ba1',
    authDomain: 'fluttersample-29ba1.firebaseapp.com',
    storageBucket: 'fluttersample-29ba1.firebasestorage.app',
    measurementId: 'G-E3E3R4XDLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoXJDDhwZpimSaQuv-cQU4vY49djE_VBE',
    appId: '1:859187312433:android:f8cf5824281c88a4f96210',
    messagingSenderId: '859187312433',
    projectId: 'fluttersample-29ba1',
    storageBucket: 'fluttersample-29ba1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc6mtTTwUxHSMdvTLZXD_X94WZw4kKVw8',
    appId: '1:859187312433:ios:0171a8bb32913c35f96210',
    messagingSenderId: '859187312433',
    projectId: 'fluttersample-29ba1',
    storageBucket: 'fluttersample-29ba1.firebasestorage.app',
    iosBundleId: 'com.example.flutterSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc6mtTTwUxHSMdvTLZXD_X94WZw4kKVw8',
    appId: '1:859187312433:ios:0171a8bb32913c35f96210',
    messagingSenderId: '859187312433',
    projectId: 'fluttersample-29ba1',
    storageBucket: 'fluttersample-29ba1.firebasestorage.app',
    iosBundleId: 'com.example.flutterSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEMHXFVz9FaGJOzUcjRX3qmODSuw3b6VI',
    appId: '1:859187312433:web:6ebcc24b4fec6766f96210',
    messagingSenderId: '859187312433',
    projectId: 'fluttersample-29ba1',
    authDomain: 'fluttersample-29ba1.firebaseapp.com',
    storageBucket: 'fluttersample-29ba1.firebasestorage.app',
    measurementId: 'G-PH6JSHVBXR',
  );
}
